name: Deploy Next.js application

on:
  push:
    branches:
      - deploy-with-docker-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env && echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
      - name: Build docker image
        run: docker build -t venatsu/next-deployment .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push venatsu/next-deployment:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull venatsu/next-deployment:latest
      - name: Delete old container
        run: docker rm -f next-deployment-container  
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name next-deployment-container venatsu/next-deployment 